# Generated by Django 3.1.4 on 2023-04-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone_call', 'Phone Call'), ('in_person_meeting', 'In-Person Meeting'), ('video_call', 'Video Call'), ('social_media', 'Social Media'), ('other', 'Other')], default='email', max_length=30),
            preserve_default=False,
        ),
    ]
