# Generated by Django 3.1.4 on 2023-04-21 12:40

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('web', '0002_interaction_interaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
    ]
