# Generated by Django 3.1.4 on 2023-04-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_lead_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='facebook_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
